name: Build

on:
  [push,workflow_dispatch]

jobs:
  unit:
    continue-on-error: true
    runs-on: ${{ matrix.runner_type }}
    strategy:
      matrix:
        runner_type: [f64s]
        #runner_type: [ds2v2,ds2v3,d2dsv4,d2asv4,d4asv4,ds3v2,ds4v2,ds5v2,f2s,f4s,f8s,f16s,f32s,f64s,ubuntu-latest]
    env:
      runId: ${{ matrix.runner_type }}-${{ github.workflow }}
      artifactsDir: artifacts/${{ github.repository }}
      iostatFile: artifacts/${{ github.repository }}/${{ matrix.runner_type }}-iostat.txt
      vmstatFile: artifacts/${{ github.repository }}/${{ matrix.runner_type }}-vmstat.txt
      timingFile: artifacts/${{ github.repository }}/${{ matrix.runner_type }}-timing.txt

    steps:
      # Start collecting stats
      #- run: sudo apt -y install sysstat
      - run: mkdir -p ${{ runner.temp }}/${{ env.artifactsDir }}
      - run: iostat -yxmt 1 > ${{ runner.temp }}/${{ env.iostatFile }} &
      - run: vmstat -n 1 > ${{ runner.temp }}/${{ env.vmstatFile }} &
      - run: date -R > ${{ runner.temp }}/${{ env.timingFile }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Lerna bootstrap
        run: yarn lerna bootstrap
      - name: Lerna tsc
        run: yarn lerna run --concurrency 1 tsc
      - name: Lerna test
        run: yarn lerna run --concurrency 1 unit
  
        # Collect/upload stats
      - run: date -R >> ${{ runner.temp }}/${{ env.timingFile }}
      - run: pkill iostat && pkill vmstat
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: perfdata
          path: ${{ runner.temp }}/${{ env.artifactsDir }}
          if-no-files-found: error

  process:
    name: Process Perf Data
    runs-on: ubuntu-latest
    needs: [lighthouseci]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - uses: actions/checkout@v2
        with:
          repository: pjquirk/runnerperf
          path: runnerperf
      - uses: actions/checkout@v2
        with:
          repository: pjquirk/iostat-tool
          path: runnerperf/iostat-tool
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2  
        with:
          name: perfdata
          path: runnerperf/data
      - name: Prereqs
        run: sudo apt -y install datamash  
      - name: Process stats
        run: |
          cd runnerperf
          (cd iostat-tool && python setup.py develop)
          ls -l data
          script/dumpcsv.sh data output
          script/aggregate.sh output ${{ github.repository }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: summary-perfdata
          path: runnerperf/output/summary.csv
          if-no-files-found: error
